create_user('Dela Cruz', 'Aaron', 'Savings Account', 13000, 'Male');
create_user('Garcia', 'Belen', 'Savings Account', 28000, 'Female');
create_user('Reyes', 'Carl', 'Savings Account', 15000, 'Male');
create_user('Ramos', 'Daisy', 'Savings Account', 18000, 'Female');
create_user('Mendoza', 'Earl', 'Savings Account', 23000, 'Male');
create_user('Santos', 'Faith', 'Savings Account', 22000, 'Female');
create_user('Flores', 'Gale', 'Savings Account', 21000, 'Male');
create_user('Gonzales', 'Hannah', 'Savings Account', 17000, 'Female');
create_user('Bautista', 'Ian', 'Savings Account', 13000, 'Male');
create_user('Villanueva', 'Janine', 'Savings Account', 28000, 'Female');
create_user('Fernandez', 'Keith', 'Savings Account', 15000, 'Male');
create_user('Cruz', 'Lani', 'Savings Account', 18000, 'Female');
create_user('De Guzman', 'Marty', 'Savings Account', 23000, 'Male');
create_user('Lopez', 'Noreen', 'Savings Account', 22000, 'Female');
create_user('Perez', 'Oliver', 'Savings Account', 21000, 'Male');
create_user('Castillo', 'Paula', 'Savings Account', 17000, 'Female');
create_user('Francisco', 'Quincy', 'Savings Account', 13000, 'Male');
create_user('Rivera', 'Rachelle', 'Savings Account', 28000, 'Female');
create_user('Aquino', 'Shane', 'Savings Account', 15000, 'Male');
create_user('Castro', 'Tanya', 'Savings Account', 18000, 'Female');
create_user('Sanchez', 'Uriel', 'Savings Account', 23000, 'Male');
create_user('Torres', 'Valerie', 'Savings Account', 22000, 'Female');
create_user('De Leon', 'Walter', 'Savings Account', 21000, 'Male');
create_user('Domingo', 'Xena', 'Savings Account', 17000, 'Female');
create_user('Martinez', 'Yves', 'Savings Account', 21000, 'Male');
create_user('Rodriguez', 'Zofia', 'Savings Account', 17000, 'Female');